language: python
addons:
  apt:
    packages:
    - wget

python:
  - "3.6"
install:
  - pip install -r ./requirements/test.txt
  - pip install codecov
  - mkdir influxdb_install
  - wget https://dl.influxdata.com/influxdb/releases/influxdb_1.5.3_amd64.deb
  - sudo dpkg -i influxdb_1.5.3_amd64.deb
  - sudo service influxdb start
script:
  - pytest --cov=server --cov-report= server/test
  - flake8 ./server/
after_success:
  - codecov
