language: python
addons:
  apt:
    packages:
    - wget

python:
  - "3.6"
install:
  - pip install -r ./requirements/test.txt
  - mkdir influxdb_install
  - wget https://dl.influxdata.com/influxdb/releases/influxdb_1.5.3_amd64.deb
  - sudo dpkg -i influxdb_1.5.3_amd64.deb
script:
  - pytest
