database:
  name: eb_logs_poc
  host: localhost
  port: 8086
  username: ""
  password: ""

log:
  measurement: eb_logins
  user_id: user_id
  sp_id: sp_entity_id_tag
  idp_id: idp_entity_id_tag

measurements:
  - time_span: 1m
    ancestor: null
  - time_span: 5m
    ancestor: 1m
  - time_span: 15m
    ancestor: 5m

api_users:
  - name: "dashboard"
    password: "secret"
  - name: "sysadmin"
    password: "secret"
