database:
  name: eb_logs_test
#  name: prod_logins
  host: localhost
  port: 8086
  username: ""
  password: ""

syslog:
  host: localhost
  port: 514

log:
  measurement: eb_logins_tst
#  measurement: EBAUTH
  user_id: user_id
  sp_id: sp_entity_id
  idp_id: idp_entity_id

secret_key: secret
product: OpenConext
supported_language_codes: en,nl,pt

api_users:
  - name: "dashboard"
    password: "secret"
    scope: "read"
  - name: "sysadmin"
    password: "secret"
    scope: "read, write"

manage:
  url: https://manage.example.surfconext.nl
  user: user
  password: secret
  mock: True

base_url: http://localhost:8080/static