FROM ghcr.io/openconext/openconext-basecontainers/python3:latest AS stats-server

COPY requirements/base.txt /requirements_base.txt
RUN pip install -r /requirements_base.txt

COPY server/ /app/server/

RUN mkdir /app/log/

WORKDIR /app
CMD ["/usr/local/bin/gunicorn", "--worker-class", "eventlet", "--workers", "8", "--bind", "0.0.0.0:80", "server.__main__:app"]
