---
name: Deploy

on:
  push:
    tags:
      - "*"
  workflow_dispatch:

jobs:
  deployment:
    permissions:
      packages: write
    environment: deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
        with:
          # we need a full checkout to be able use git describe.
          # see https://github.com/actions/checkout/issues/1471
          fetch-depth: 0
          fetch-tags: true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for GUI Docker
        id: meta_gui
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/openconext/openconext-stats/stats-gui
          flavor: |
            latest=false
          tags: |
            type=ref,event=tag
            type=raw,event=tag,value=latest
            type=semver,event=tag,pattern={{version}}
            type=raw,event=workflow_dispatch,value=snapshot

      - name: Extract metadata (tags, labels) for Server Docker
        id: meta_server
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/openconext/openconext-stats/stats-server
          flavor: |
            latest=false
          tags: |
            type=ref,event=tag
            type=raw,event=tag,value=latest
            type=semver,event=tag,pattern={{version}}
            type=raw,event=workflow_dispatch,value=snapshot

      - name: Save version info
        run: |
          git describe --exclude 'snapshot' | tee ./server/api/version.info
          git log -1 | tee ./server/api/git.info

      - name: Build and push the stats gui image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/Dockerfile.frontend
          platforms: "linux/amd64, linux/arm64"
          push: true
          tags: ${{ steps.meta_gui.outputs.tags }}
          labels: ${{ steps.meta_gui.outputs.labels }}

      - name: Build and push the stats server image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/Dockerfile.server
          platforms: "linux/amd64, linux/arm64"
          push: true
          tags: ${{ steps.meta_server.outputs.tags }}
          labels: ${{ steps.meta_server.outputs.labels }}
